
CREATE TABLE `active_drivers` (

--IDENTIFICADORES NUMERICOS
    `id` BIGINT(20) UNSIGNED NOT NULL ,
    `driver_id` BIGINT(20) UNSIGNED NOT NULL ,

--INDENTIFICADORES DE TIEMPO
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

--LLAVE PRIMARIA
    PRIMARY KEY (id)

)

--PROTOCOLO DE CARACTERES ACEPTADOS PARA INSERTAR Y RECIBIR DATOS
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;
